# Generated by Django 5.2.13 on 2026-04-26 11:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partner_api_setting_api_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='core_apireq_user_id_4b1e2b_idx',
            old_name='core_apilog_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='core_apireq_request_eb3dc7_idx',
            old_name='core_apilog_request_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='core_apireq_status__f4e350_idx',
            old_name='core_apilog_status_idx',
        ),
        migrations.AlterField(
            model_name='partnerapisetting',
            name='api_key',
            field=models.CharField(db_index=True, default=core.models.generate_api_key, max_length=128, unique=True),
        ),
    ]
