# Generated by Django 5.2.13 on 2026-05-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_onboarding_application'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingapplication',
            new_name='core_onboar_status_5db439_idx',
            old_name='core_onboar_status_f3f8b6_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingapplication',
            new_name='core_onboar_mobile_6f62bb_idx',
            old_name='core_onboar_mobile_535ab4_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingapplication',
            new_name='core_onboar_parent__ddb0c6_idx',
            old_name='core_onboar_parent__b9e831_idx',
        ),
    ]
