# Generated by Codex on 2026-05-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_core_onboar_status_f3f8b6_idx_core_onboar_status_5db439_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("aeps", "AEPS"),
                    ("utility", "Utility"),
                    ("recharge", "Recharge"),
                    ("dmt", "DMT"),
                    ("payout", "Payout"),
                    ("payment_gateway", "Payment Gateway"),
                    ("verification", "Verification"),
                    ("notification", "Notification"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("aeps", "AEPS"),
                    ("billpay", "Utility Bill Payment"),
                    ("recharge", "Recharge"),
                    ("dmt", "DMT"),
                    ("express_money", "Express Money"),
                    ("payout", "Payout"),
                    ("account_verify", "Account Verification"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AepsMerchantProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_login_id", models.CharField(db_index=True, max_length=80, unique=True)),
                ("merchant_phone_number", models.CharField(max_length=20)),
                ("super_merchant_id", models.PositiveIntegerField(default=0)),
                ("fingpay_merchant_status", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("onboarding_pending", "Onboarding Pending"),
                            ("onboarded", "Onboarded"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=30,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("otp_sent", "OTP Sent"),
                            ("otp_validated", "OTP Validated"),
                            ("biometric_pending", "Biometric Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=30,
                    ),
                ),
                ("device_imei", models.CharField(blank=True, max_length=80)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("merchant_state", models.PositiveIntegerField(blank=True, null=True)),
                ("merchant_city_name", models.CharField(blank=True, max_length=80)),
                ("merchant_district_name", models.CharField(blank=True, max_length=80)),
                ("merchant_pin_code", models.CharField(blank=True, max_length=12)),
                ("company_legal_name", models.CharField(blank=True, max_length=160)),
                ("company_type", models.PositiveIntegerField(blank=True, null=True)),
                ("company_bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_ifsc_code", models.CharField(blank=True, max_length=20)),
                ("settlement_account_last4", models.CharField(blank=True, max_length=4)),
                ("bank_account_name", models.CharField(blank=True, max_length=160)),
                ("primary_key_id", models.PositiveIntegerField(blank=True, null=True)),
                ("encode_fp_txn_id", models.CharField(blank=True, max_length=160)),
                ("onboarding_response", models.JSONField(blank=True, default=dict)),
                ("ekyc_response", models.JSONField(blank=True, default=dict)),
                ("last_provider_message", models.CharField(blank=True, max_length=240)),
                ("rejection_reason", models.TextField(blank=True)),
                ("last_onboarded_at", models.DateTimeField(blank=True, null=True)),
                ("last_ekyc_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aeps_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__mobile"],
                "indexes": [
                    models.Index(fields=["status", "kyc_status"], name="core_aepsme_status_560cf1_idx"),
                    models.Index(fields=["merchant_login_id"], name="core_aepsme_merchan_74ed02_idx"),
                ],
            },
        ),
    ]
